name: Bug Report
description: File a bug report if something isn't working as expected.
title: "[Bug]: "
labels: ["bug", "todo"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      value: "Briefly describe the problem you are having in a few paragraphs."
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version were you running?
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant output.
  - type: textarea
    id: additional-details
    attributes:
      label: Additional details
      description: Do you have any other details to share?
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Sh4dow-BR/S3/blob/master/docs/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true